[package]
name = "chisel"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
edition = "2018"

[dependencies]
cursive = "0.13.0"

[lib]
name = "chisel_core"
path = "lib/lib.rs"

[[bin]]
name = "chisel"
path = "src/main.rs"
