[tasks.update-tools]
dependencies = [
    "update-layoutflash",
    "update-buildtool",
    ]

[tasks.update-layoutflash]
extend = "update-tool-generic"
cwd = "tools/layoutflash"

[tasks.update-buildtool]
extend = "update-tool-generic"
cwd = "tools/chisel"

[tasks.update-tool-generic]
private = true
command = "cargo"
args = [ "install", "-f", "--path", "." ]

[tasks.setup]
dependencies = [
    "install-dependencies",
    "update-tools"
]

[tasks.install-dependencies]
private = true
dependencies = [
    "install-binutils",
    "install-llvm-tools",
]

[tasks.install-binutils]
private = true
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [ "objcopy", "--help" ] }

[tasks.install-llvm-tools]
private = true
install_crate = { rustup_component_name = "llvm-tools-preview" }
