[package]
name = "ast25x0"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2018"
build = "build.rs"

[dependencies]
model = { path = "../../../drivers/model" }
soc = { path = "../../../soc/aspeed/ast2500" }

[dependencies.uart]
path = "../../../drivers/uart"
features = ["aspeed"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
