[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/s390x-unknown-none/debug"
RUST_TARGET_PATH = "${OREBOOT}/src/cpu/ibm/s390x"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/s390x-unknown-none/release"
RUST_TARGET_PATH = "${OREBOOT}/src/cpu/ibm/s390x"

[tasks.default]
dependencies = ["bootblob"]

[tasks.bootblob]
dependencies = [ "build" ]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "${TARGET_DIR}/oreboot", "${TARGET_DIR}/bootblob.bin"]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.run]
command = "qemu-system-s390x"
args = ["-m", "512", "-serial", "mon:stdio", "-display", "none",
	"-kernel", "${TARGET_DIR}/bootblob.bin"]

[tasks.objdump]
dependencies = ["build"]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/oreboot"]
